# Generated by Django 6.0.1 on 2026-02-01 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_code_created_at_user_email_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
